function impacts = importImpacts(filename)
%%importWyo
    %Import a SINGLE sounding file in IMPACTS/UWyo format.
    %Only pressure, height, temperature, and dewpoint data are imported.
    %General form: [impacts] = importImpacts(filename);

    % textscan call auto-generated by MATLAB on 2020/01/24 11:15:06
    %Version date: 1/24/2020
    %Last major revision: 1/24/2020
    %Written by: Daniel Hueholt
    %North Carolina State University
    %Undergraduate Research Assistant at Environment Analytics
    %

% %% Initialize variables.
% if nargin<=2
%     startRow = 1;
%     endRow = inf;
% end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%6f%7f%7f%7f%[^\n\r]';

%% Open as character block
rawChar = fileread(filename);
denoteStart = '-----------------------------------------------------------------------------'; % 77 hyphens
denoteEnd = '</PRE><H3>';
dashBlock = strfind(rawChar,denoteStart);
dataStart = dashBlock(2)+77;
dataEnd = strfind(rawChar,denoteEnd);


%% Open the text file.
%fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
%dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
%for block=2:length(startRow)
%    frewind(fileID);
%    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
%    for col=1:length(dataArray)
%        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
%    end
%end

%% Close the text file.
%fclose(fileID);

%% Create output variable
dataArray = textscan(rawChar(dataStart:dataEnd), formatSpec,'Delimiter','','WhiteSpace','','TextType','string','EndOfLine','\r\n');
impacts = table(dataArray{1:end-1}, 'VariableNames', {'pressure','height','temp','dewpt'});
end

