function [impacts] = importImpacts(filename)
%%importImpacts
    %Import a SINGLE sounding in IMPACTS/UWyo format.
    %Only pressure, height, temperature, and dewpoint data are imported.
    %Written for aircraft flight planning support during NASA IMPACTS 2020
    %deployment.
    %
    %General form: [impacts] = importImpacts(filename);
    %
    %Output
    %impacts: a table of sounding data
    %
    %Input
    %filename: a filename in ops.text_sounding.YYYYMMDDHH.SSS.txt format
    %
    %textscan call auto-generated by MATLAB on 2020/01/24 11:15:06
    %
    %Version date: 1/24/2020
    %Last major revision: 1/24/2020
    %Written by: Daniel Hueholt
    %North Carolina State University
    %Undergraduate Research Assistant at Environment Analytics
    %

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%6f%7f%7f%7f%[^\n\r]';

%% Open as character block
rawChar = fileread(filename);
denoteStart = '-----------------------------------------------------------------------------'; % 77 hyphens
denoteEnd = '</PRE><H3>';
dashBlock = strfind(rawChar,denoteStart);
dataStart = dashBlock(2)+77;
dataEnd = strfind(rawChar,denoteEnd);

%% Create output variable
dataArray = textscan(rawChar(dataStart:dataEnd), formatSpec,'Delimiter','','WhiteSpace','','TextType','string','EndOfLine','\r\n');
impacts = table(dataArray{1:end-1}, 'VariableNames', {'pressure','height','temp','dewpt'});

%% Bind metadata from filename to table
date_string = filename(19:30);
valid_date_num = datenum(date_string,'YYYYMMDDHH');
launch_site = filename(32:34);
impacts = addprop(impacts,{'date_string','valid_date_num','launch_site'},{'table','table','table'});
impacts.Properties.CustomProperties.date_string = date_string;
impacts.Properties.CustomProperties.valid_date_num = valid_date_num;
impacts.Properties.CustomProperties.launch_site = launch_site;

end

